# Generated by Django 2.2.2 on 2019-06-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('duration_in_months', models.IntegerField(max_length=50)),
                ('course_number', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
