# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-14 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_teachers_image'),
        ('course', '0002_auto_20190605_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teachers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='teachers.Teachers'),
        ),
    ]
