# Generated by Django 2.2.2 on 2019-06-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20190601_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.FileField(blank=True, upload_to='post_image'),
        ),
    ]
