# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-14 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20190605_1951'),
        ('student', '0005_auto_20190613_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ManyToManyField(related_name='students', to='course.Course'),
        ),
    ]
