# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-14 14:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_student_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='course',
            new_name='courses',
        ),
    ]
